version: 2
workflows:
    version: 2
    main:
        jobs:
            - test_py27
            - test_py36
            - test_py37
            - test_pypy3
            - publish:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/

jobs:
    test_py27:
        docker:
            - image: python:2.7.15-alpine3.8
        steps:
            - checkout
            - run: apk update && apk add alpine-sdk
            - run: cat Pipfile | grep -v flit > Pipfile2
            - run: mv Pipfile2 Pipfile
            - run: pip install pipenv==2018.10.13
            - run: pipenv --python $(which python) install --dev
            - run: pipenv run pytest --cov pygetty --cov-report term-missing --cov-report xml
    test_py36:
        docker:
            - image: python:3.6.6-alpine3.8
        steps:
            - checkout
            - run: apk update && apk add alpine-sdk
            - run: pip install pipenv==2018.10.13
            - run: pipenv --python $(which python) install --dev
            - run: make test
    test_py37:
        docker:
            - image: python:3.7.0-alpine3.8
        steps:
            - checkout
            - run: apk update && apk add alpine-sdk
            - run: pip install pipenv==2018.10.13
            - run: pipenv --python $(which python) install --dev
            - run: make test
    test_pypy3:
        docker:
            - image: pypy:3-6.0.0-slim
        steps:
            - checkout
            - run: apt-get update && apt-get install -y build-essential
            - run: pip install pipenv==2018.10.13
            - run: pipenv --python $(which pypy3) install --dev
            - run: make test
    publish:
        docker:
            - image: python:3.7.0-alpine3.8
        steps:
            - run: apk update
            - run: apk add git openssh
            - checkout
            - run: pip install pipenv==2018.10.13
            - run: pipenv --python $(which python) install --dev
            - run: pipenv run flit build
            - run: pipenv run flit publish
